version: "3.8"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: gunicorn polling_project.wsgi:application --bind 0.0.0.0:8000
    container_name: easypolls
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
